meta_product_name: "Cargo"
meta_title: "Cargo - Next level delivery"
meta_description: "Fast, Cheap and Sustainable"
meta_image: "cargo-logo-meta-tag4.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
